Finished initialize frontend
WildCodeSchool/2024-02-wns-bleu-wetransfer pull request #23
Opened 2024-07-03 15:12 UTC by Gessmass

Finished initialize frontend

2024-07-03 15:16 UTC, LuckyShuii approved these changes

2024-07-04 07:25 UTC, MaximeG971 requested changes

2024-07-04 07:25 UTC, MaximeG971 commented on frontend/src/pages/AccessPage.tsx
> +		<Acceespagewrapper>{location.pathname}</Acceespagewrapper>
'AccessPageWrapper' instead of 'Accees' ?

2024-07-04 07:25 UTC, MaximeG971 commented on frontend/src/pages/AccessPage.tsx
> +const Acceespagewrapper = styled.div`
Same here ?

2024-07-04 07:53 UTC, LuckyShuii requested changes

2024-07-04 07:53 UTC, LuckyShuii commented on frontend/package.json
> +}
Rajouter graphQL et ApolloClient
https://github.com/karimmakhloufi/cda-bleu-02-2024/blob/main/the-good-corner/frontend/package.json

2024-07-04 07:59 UTC, LuckyShuii approved these changes

2024-07-04 07:59 UTC, MaximeG971 approved these changes

2024-07-04 08:00 UTC, merged